### ISSUE TITLE
Using a mature name for the repo aligned with our non formalized sexy naming schema

### ISSUE THREAD

**Issue by gwarf** [EGI-Foundation/ansible-role-VOMS-client#1]
OCD striking...

It may be appropriate to rename the project to ansible-* something to remain aligned with the usual naming scheme we are using and that was used for all the other ansible-related components.
We may or may not also want to use some specific casing.

**Comment by brucellino** [comment]
Totally down with this. Will take a look at it soon.

**Comment by brucellino** [comment]
I've changed the name of the repo to `ansible-VOMS-client-role` - still haven't added this to the style guide, but closing this issue in the meantime. You cool with this @gwarf ?

**Comment by gwarf** [comment]
Sounds perfect.
Still, I think that an issue name containing the words mature and sexy may not be that much appropriate ;)

**Comment by enolfc** [comment]
Can we agree on the naming schema? I was using ansible-role-* instead of ansible-*-role as here. Don't mind going either way, but we should converge

**Comment by gwarf** [comment]
Even if I've been using the ansible-*-role model I think that ansible-role-* is more sensible. It's also what is used in some of the examples on Ansible galaxy: https://galaxy.ansible.com/intro

**Comment by brucellino** [comment]
OK ! repo name is now `/(ansible-role)([a-z]+)/`
